services:
  clean-pdf:
    image: ghcr.io/ekwoodrich/clean-pdf-ebook:main
    volumes:
      - ./input:/input
      - ./output:/output
      - ./archive:/archive
    environment:
      - INPUT_DIR=/input
      - OUTPUT_DIR=/output
      - ARCHIVE_DIR=/archive
      - FLAGS=-l 3 --deskew --cover
