services:
  clean-pdf:
    image: ghcr.io/ekwoodrich/clean-pdf-ebook:main
    volumes:
      - ./input:/input
      - ./output:/output
      - ./archive:/archive
      - ./failed:/failed
    environment:
      - INPUT_DIR=/input
      - OUTPUT_DIR=/output
      - ARCHIVE_DIR=/archive
      - FAILED_DIR=/failed
      - FLAGS=-l 3 --ocrmypdf --deskew --cover
